platform: idf
target: esp32c3
flash_size: 4MB
filesystem: spiffs
components:
  - esp_app_format
  - app_update
  - esp_event
  - esp_http_server
  - esp_netif
  - esp_partition
  - esp_wifi
  - nvs_flash
